development: &defaults
  adapter: postgresql
  encoding: unicode
  database: <%= ENV.fetch('DATABASE_NAME') %>
  username: <%= ENV.fetch('DATABASE_USERNAME') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') %>

test:
  <<: *defaults
  database: orientation_test
