language: python

sudo: false

python:
- nightly
- 3.5
- 3.4
- 3.3
- 3.2
- 2.7
- pypy

matrix:
  allow_failures:
  - python: nightly

addons:
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - gfortran

before_install:
- SEDPROGRAM='s/[^0-9]//g;s/.//3g;2s/.*/py/;1!G;h;$!d;s/y.2./y/'
- PY=$(python -V 2>&1 | sed "$SEDPROGRAM")
- test $PY == 32 && TOX='virtualenv<14 tox' || TOX=tox
- export TOXENV=py$PY-travis

install:
- pip install $TOX
- |
  # Workaround to show the log (avoids the Travis timeout)
  fname="/tmp/tox_audiolazy/$TOXENV/log/$TOXENV-1.log"
  for ((;;)) ; do
    sleep 5
    if [ -e $fname ] ; then
      tail -F "$fname"
    fi ;
  done &
- tox -vv --notest
- kill %1 # The for loop with the tail command

script: tox -vv
