-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: 97b88d9610bcc03982ddac33caba98bb2b751f5f
    hooks:
    -   id: autopep8-wrapper
        exclude: (docs/conf.py|tests/messages/data/)
    -   id: check-added-large-files
    -   id: check-docstring-first
        exclude: (docs/conf.py)
    -   id: check-json
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: flake8
        exclude: (docs/conf.py|babel/messages/__init__.py|babel/__init__.py|babel/_compat.py|tests/messages/data|scripts/import_cldr.py)
    -   id: name-tests-test
        args: ['--django']
        exclude: (tests/messages/data/)
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
