install:
  - pip install pytest

docker:
  as_root: true  # for pip installation
  image: "coala/rultor-python"

merge:
  fast-forward: only
  rebase: true
  script:
    - echo "Nothing to do (yet!)"
